2025-05-25T21:50:22.877255 [ERROR] [POST ERROR] HTTPConnectionPool(host='100.116.147.6', port=5000): Max retries exceeded with url: /soil-data (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x74b91c10>, 'Connection to 100.116.147.6 timed out. (connect timeout=5)'))
2025-05-25T21:50:22.877768 [ERROR] Failed payload: {"timestamp": "2025-05-25T21:50:17.820456", "moisture": 14, "wetness_percent": 0.0, "lux": 1728.631199186992, "sensor_id": "pi_zero_1"}
2025-05-25T21:50:29.380484 [ERROR] [POST ERROR] HTTPConnectionPool(host='100.116.147.6', port=5000): Max retries exceeded with url: /soil-data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x741e5dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-25T21:50:29.381051 [ERROR] Failed payload: {"timestamp": "2025-05-25T21:50:29.195681", "moisture": 14, "wetness_percent": 0.0, "lux": 1728.9808943089429, "sensor_id": "pi_zero_1"}
2025-05-25T21:50:36.038840 [ERROR] [POST ERROR] HTTPConnectionPool(host='100.116.147.6', port=5000): Max retries exceeded with url: /soil-data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x741eba50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-25T21:50:36.039315 [ERROR] Failed payload: {"timestamp": "2025-05-25T21:50:35.850815", "moisture": 14, "wetness_percent": 0.0, "lux": 1728.4358739837396, "sensor_id": "pi_zero_1"}
2025-05-26T12:39:49.497470 [ERROR] [POST ERROR] HTTPConnectionPool(host='100.116.147.6', port=5000): Max retries exceeded with url: /soil-data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7424f530>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-26T12:39:49.515560 [ERROR] Failed payload: {"timestamp": "2025-05-26T12:39:49.030014", "moisture": 14, "wetness_percent": 0.0, "lux": 1728.8265243902438, "sensor_id": "pi_zero_1"}
2025-05-26T12:39:55.937620 [ERROR] [POST ERROR] HTTPConnectionPool(host='100.116.147.6', port=5000): Max retries exceeded with url: /soil-data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7425a130>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-26T12:39:55.938218 [ERROR] Failed payload: {"timestamp": "2025-05-26T12:39:55.781537", "moisture": 14, "wetness_percent": 0.0, "lux": 1729.0691056910568, "sensor_id": "pi_zero_1"}
2025-05-26T12:40:02.341279 [ERROR] [POST ERROR] HTTPConnectionPool(host='100.116.147.6', port=5000): Max retries exceeded with url: /soil-data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7425ad90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-26T12:40:02.341762 [ERROR] Failed payload: {"timestamp": "2025-05-26T12:40:02.196628", "moisture": 14, "wetness_percent": 0.0, "lux": 1729.7212398373986, "sensor_id": "pi_zero_1"}
2025-05-26T14:00:43.449468 [ERROR] [POST ERROR] HTTPConnectionPool(host='100.116.147.6', port=5000): Max retries exceeded with url: /soil-data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7685bb10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-26T14:00:43.450719 [ERROR] Failed payload: {"timestamp": "2025-05-26T14:00:41.928103", "moisture": 14, "wetness_percent": 0.0, "lux": 1730.5907520325209, "sensor_id": "pi_zero_1"}
2025-05-26T14:00:49.946280 [ERROR] [POST ERROR] HTTPConnectionPool(host='100.116.147.6', port=5000): Max retries exceeded with url: /soil-data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7426a390>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-26T14:00:49.946873 [ERROR] Failed payload: {"timestamp": "2025-05-26T14:00:49.830638", "moisture": 14, "wetness_percent": 0.0, "lux": 1731.8351626016265, "sensor_id": "pi_zero_1"}
2025-05-26T14:00:56.379914 [ERROR] [POST ERROR] HTTPConnectionPool(host='100.116.147.6', port=5000): Max retries exceeded with url: /soil-data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7426afb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-26T14:00:56.381182 [ERROR] Failed payload: {"timestamp": "2025-05-26T14:00:56.241846", "moisture": 14, "wetness_percent": 0.0, "lux": 1730.8333333333337, "sensor_id": "pi_zero_1"}
2025-05-26T14:55:28.944033 [ERROR] [POST ERROR] HTTPConnectionPool(host='100.116.147.6', port=5000): Max retries exceeded with url: /soil-data (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x749d1130>, 'Connection to 100.116.147.6 timed out. (connect timeout=5)'))
2025-05-26T14:55:28.945338 [ERROR] Failed payload: {"timestamp": "2025-05-26T14:55:23.909455", "moisture": 15, "wetness_percent": 0.14285714285714285, "lux": 1361.7915650406505, "sensor_id": "pi_zero_1"}
